In [1]:
import os

import tensorflow as tf

import cProfile

In [9]:
tf.executing_eagerly()

True

In [8]:
x = [[2.]]
print(x)
m = tf.matmul(x, x)
print(m)
print("hello, {}".format(m))

[[2.0]]
tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
hello, [[4.]]


In [11]:
a = tf.constant([[1, 2],
                 [3, 4]])
# Broadcasting support
b = tf.add(a, 1)
print(b)

# Operator overloading is supported
print(a * b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [12]:
# Use NumPy values
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [14]:
# Obtain numpy value from a tensor:
print(a.numpy())

[[1 2]
 [3 4]]


In [21]:
def fizzbuzz(max_num):
  counter = tf.constant(0)

  print('c', counter)
  max_num = tf.convert_to_tensor(max_num)
  print(max_num)
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num%3) == 0 and int(num%5)==0:
      print('FizzBuzz')
    elif int(num % 3) == 0:
      print('Fizz')
    elif int(num % 5) == 0:
      print('Buzz')
    else:
      print(num.numpy())
    counter += 1
  
fizzbuzz(15)

c tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [22]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = w * w

grad = tape.gradient(loss, w)
print(grad)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [23]:
# Fetch and format the mnist data
(mnist_images, mnist_labels), _ = tf.keras.datasets.mnist.load_data()



11493376/11490434 [==============================] - 0s 0us/step


In [24]:
dataset = tf.data.Dataset.from_tensor_slices(
  (tf.cast(mnist_images[...,tf.newaxis]/255, tf.float32),
   tf.cast(mnist_labels,tf.int64)))
dataset = dataset.shuffle(1000).batch(32)


In [25]:
# Build the model
mnist_model = tf.keras.Sequential([
  tf.keras.layers.Conv2D(16,[3,3], activation='relu',
                         input_shape=(None, None, 1)),
  tf.keras.layers.Conv2D(16,[3,3], activation='relu'),
  tf.keras.layers.GlobalAveragePooling2D(),
  tf.keras.layers.Dense(10)
])